
name: oauth2-proxy
namespace: default

OAUTH2_PROXY_CLIENT_ID: feced7094f224d98d194

secretName: oauth2-proxy-secret
OAUTH2_PROXY_CLIENT_SECRET: AgCmPXC5Rl8z+jgVafdLDT4o0rYVUjA+5krLb9UejtnxI0ciflpXzBFA1v6NXQEWhXlsf6ODAdzHq3UYSva/0UivVAEdnoxsSrjVhnY4wDTre2NW+SSgDsRPab3Lm2m+IADH60TgYfgpfWohIi5iVr/FUGt62+BkITYUnGd1qOVTD8WTkYrqML3+ZhfTRRP5wToVV8XGsHlSoxEqp+6sMHOS9Z0gciCWlz5vM6UfIyYaiAl7VzQNubykPwCoxMBCHJG2ZMKhI3qNGjDXFZSNt8tUfb+4yoB5XYc8RmMcrcoR0gvBpnuIEe8BK65mNFgRCrXdsVPWZp/GL+YH2spduxpyfYUrq2VaktmEE3kflzM9lkfblH7Tt5+P+uEDs6xqOyNvtZiya0tNKvxY6GJnP3L6pYzuQjW75AcPMpI73wyBDuziay3BUIFYpgjV57hBJ76sJSuSbk9VeAYElPkAOXbAGIX5bPz8HPY2R78IuB4wRA7UOnz+FbmRweR1bF4DLnImB5eWIyceAZHWp4MrH+A5y6/aLV6zNK7vOrKrjXLX3M61maYhTuBnMep1rA9DvOgxZeURVX18csSJCIcqfHqNcqnoZuUMhli/IEa0Mt8Q4oo/z2qKGZrRrnC+KgvJWqvDi4nCpBVxGNkHvOfzjFBpSzxERmJuJmPIulTXqhTriD/hfsgxTX81c/Pj8bF3xpHx9IGiGV/h5x485yXuOGazCytZZ8HzUN1LSbWSR7rlbBztzcINUWUh

#gnereate OAUTH2_PROXY_COOKIE_SECRET by:
# docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
OAUTH2_PROXY_COOKIE_SECRET: UUFZNFFLLzZ2amo4bVlnLzlnNmZxUT09


configmapName: authenticated-emails
data:
  authenticated-emails.txt: |
    hossam.radwan.engineer@gmail.com
    michael.puehringer@datavisyn.io
    vanessa.stoiber@datavisyn.io

