kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: "{{ .Values.secretName }}"
  namespace: "{{ .Values.namespace }}"
spec:
  template:
    metadata:
      name: "{{ .Values.secretName }}"
      namespace: "{{ .Values.namespace }}"
    data:
  encryptedData:
    OAUTH2_PROXY_CLIENT_SECRET: "{{ .Values.OAUTH2_PROXY_CLIENT_SECRET }}"