name: mongo-express
namespace: default
imageName: mongo-express
env:
  - name: ME_CONFIG_MONGODB_ADMINUSERNAME
    valueFrom:
      secretKeyRef:
        name: mongo-express-secret
        key: mongo-root-username
  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
    valueFrom: 
      secretKeyRef:
        name: mongo-express-secret
        key: mongo-root-password
  - name: ME_CONFIG_MONGODB_SERVER
    valueFrom: 
      configMapKeyRef:
        name: mongodb-configmap
        key: database_url


serviceType: ClusterIP
serviceProtocol: TCP
servicePort: 80
serviceTargetPort: 8081
ingress:
  enabled: true 
  host: mongo.testmydemoapp.com

configmap:
  enabled: true
  configmapName: mongodb
  database_url: mongodb-service

secretName: mongo-express-secret
secretType: Opaque
mongoRootUsername: AgA+TUNObbyGe+gFWKVgVZLXCPOA2ktgmAFQkD+FkcyVgUOtmnyaov+KQvwAan71bZeaZgx/c7JtVAaSdDw3+nSZ2qzji8WHZCpByug18dkceT3QEkLRf62oG1FWrdYna15tp2JTG8Ga1yDpl7Bdv0s80i9B3Bxr2TnpkPAF2DS+4Q9AwsHG4CSDbPde2gFNRQLLeslHPzIaF24/OtRWjqWT+9Clk+jlh4Q+5yoQ+jX4e1qApAfSwYx+UgIguCQLPlpCbwburx6l1n/6nuxGhJE9mPnyc7UxrnkXfJXrkSVgjT5NsitIRi9EdiGN/4RRDS95WxRmMpOlfmatHGv3YzOZeeFNvgiszXKSjwHpKk5zmWnmftRtejfG0cHQX9EX8OV7ceRhMjCujaWic615dzIwbGGXHNkSrI8TvjiqEJ0uBIvOh/5o6xPoAWcSdoKfhaqmDaq7pbR+x71n/esyHa985Yv9RPD7iZzlAn3eD6Ez4VrTknr7V716bMBBEZQjYhKkIEpYojfY+3c8K1R5S/j/3yXsqOuHxk3xybWfwurZXvYGGljmc9HrMHvRur7ATRFxyOaCb0YSrjwViVBM7N42b0uzcbJ5X+26QYFjglL8UXXpEoiJUhOVyLP98NQdtKUSIaLrOUn2vp35UEwIH6KafRsq/mvDQ2BnpEsOT5RXKKYyuSo071xakI8uXhJdl0nQKHRlG6TK/w==
mongoRootPassword: AgBS5Wbz+jACnSRJEGyKRrsfy5wdg6UUrhXqozT5fSMRPnkGFGIPAEhZKMPcVhtgxrmxnhx7Y0faAF8kRHSHBAaLUbyrYVIC2E5zokQsOFkFBmezExDPpS4qPPqNI4v92sfFNeR7EuvjTkl0Bs31pVhMVAJRq9m+frR93fkqv4RsDmqU32Yi5Qh5/zksKqGOWqwilzUgKGcwn+xwoVwGER5JRhJs221xKo3YrOzlY2dHVRcGmA0rW5Zu+eP0se9J8a23AS6a1UoG05vVVpqhtdfJNL+z17UWtiOnsP4rZm3s0T3FBPRl1NIUSnd1BVR+OUDKkJc73EDJ0tJdeDgYPs4dI/BkavGtNKde+nExxfpcBFGABLvy/iZcIR+4d0EWpUBKlNTPwE1zO6A1t0TXTKEH0rZ1pAhYRGisnWHWKLf0hs4raJgi0ORZj/daFqmSAZr4ZigRc++3FI7brYEbG9ks3h9OQxSLQI6ZJB/e/a6xUrsrB8y+27atfKblLc2mtFpSRJ0gcic+KR+ntcNl6pP57Enlz3RKyJvzvYvL58But9Q+5UBGYrlaRIiYR8HPG7EhM13j0JUuxRmwFsi7+GNizS9P4h4rNVSDSR6+Z2KaCepvVaSa5c4eMZlB7f2ECRqDGteg786kWIxSTD1JYUGGR/ot2xXy8tdS3bfueMxAkz5R/9d7a2cfsXK9L+/IA9gWlKYnZzeeWQ==
