{{- if.Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.configmapName }}-configmap
  namespace: {{ .Values.namespace }}
data:
  database_url: {{ .Values.configmap.database_url }}
{{- end }}
