apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.imageName }}
        ports:
        - containerPort: {{ .Values.serviceTargetPort }}
      {{- with .Values.env }}
        env:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        
