kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: "{{ .Values.secretName }}"
  namespace: "{{ .Values.namespace }}"
spec:
  template:
    metadata:
      name: "{{ .Values.secretName }}"
      namespace: "{{ .Values.namespace }}"
    data:
  encryptedData:
    mongo-root-password: "{{ .Values.mongoRootPassword }}"
    mongo-root-username: "{{ .Values.mongoRootUsername }}"